### ISSUE TITLE
Should not urlencode included URL

### ISSUE THREAD

**Issue by wosc** [fastly/esi#14]
If you `<esi:include src="/foo?bar"/>`, this ends up in the subrequest as `/foo%3Fbar`.

Reproduction: https://fiddle.fastly.dev/fiddle/49211807 (mode 4, i.e. send `/urlencode` as the request), observe the stdio output (`Including ESI src=/uuid%3Ffoo=bar`)

**Comment by wosc** [comment]
I think this is due to this line: https://github.com/fastly/esi/blob/main/esi/src/lib.rs#L210 `if url.starts_with('/') { req.get_url_mut().set_path(url); }` -- set_path of course will encode `?`

**Comment by kailan** [comment]
Ah, nice find @wosc! I'll make sure to fix this before releasing `0.4.0`
